version: '2.0'

services:
  web:
    image: nickbryant/test:1.0.0
    container_name: web
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
      - SERVER_PORT=8083

    restart: always
    ports:
      - "8083:8083"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - app-net

networks:
  app-net:
    external: true
