version: '2.0'

services:
  web:
    image: nickbryant/xigua:pro-1.0.0
    container_name: xigua
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
      - SERVER_PORT=8085
      - ENV=Pro

    restart: always
    ports:
      - "8085:8085"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks:
      - app-net

networks:
  app-net:
    external: true
