version: '2.0'

services:
  web:
    image: nickbryant/aiohttp:xigua-1.0.1
    container_name: xigua
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test
      - SERVER_PORT=8085
      - ENV=Pro

    restart: always
    ports:
      - "8085:8085"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /usr/local/project/aiohttp-demo/app/static/images/:/usr/src/xigua/app/static/images/
    networks:
      - app-net

networks:
  app-net:
    external: true
